### ISSUE TITLE
please make a "setup.py" so that it can be imported easily

### ISSUE THREAD

**Issue by FieryKing93** [Categorically/OpenBullet2Python#17]
I have been trying to import this github repo but I am getting an `ERROR: File "setup.py" not found for legacy project git+https://github.com/Categorically/OpenBulletToPython.` I was importing it using `pip install git+https://github.com/Categorically/OpenBulletToPython`. How can users like me import it??

**Comment by WHITEH0ST** [comment]
Its not a Module, you can simply clone the project and set your config in the example.py file. This tool works great for me, I have made many adjustments like proxies list and combolist interaction. Will send a push request soon.
